### ISSUE TITLE
Dakboard

### ISSUE THREAD

**Issue by pateboyd** [Metro420yt/MealViewerAPI#4]
I am trying to get mealviewer on my dakboard and am not sure where to start. Do you have any guidance?

**Comment by Metro420yt** [comment]
@pateboyd 
not sure if you still need help, just seeing this.
i dont know the in's and out's of dakboard, but they have an [api](https://blog.dakboard.com/new-dakboard-api/) for their plus/pro members, if you wanted the screen to have a more custom way to show information
personally, i would probably use a calendar api, like [google calendar](https://developers.google.com/calendar/api/v3/reference) ([npm package](https://www.npmjs.com/package/googleapis)), and link a calendar to DAKboard, then make a program to query mealviewer, and [insert](https://developers.google.com/calendar/api/v3/reference/events/insert) a calendar event with that days meal info
